### ISSUE TITLE
Drag'n'drop in chrome

### ISSUE THREAD

**Issue by Nikoms** [moxiecode/plupload#1261]
Browser :  43.0.2357.124 m
When I drop an image I get: Uncaught TypeError: e.webkitGetAsEntry is not a function

I came back in 2.1.4 and it works

**Comment by jayarjo** [comment]
There was a different problem that prevented DnD from working in 2.1.5, that was fixed now in: https://github.com/moxiecode/moxie/commit/40f9e1684339ebc18ff0731793014700c5a1f9d5. But I cannot repeat `Uncaught TypeError: e.webkitGetAsEntry` error.

**Comment by jayarjo** [comment]
Try: [2.1.6](https://github.com/moxiecode/plupload/releases/tag/v2.1.6).
