### ISSUE TITLE
getSource() error after upgrade from 1.5.7 to 2.1.2

### ISSUE THREAD

**Issue by Karmalakas** [moxiecode/plupload#1230]
`Uncaught TypeError: this.getSource is not a function  plupload.full.min.js:formatted:2798`
This line is: `var e = this.getSource().getSource();`

Used Chrome Dev toolbar to format minified JS. Error appears right after file selection.

**Comment by Karmalakas** [comment]
2.1.4 still has the same issue :/

**Comment by aik099** [comment]
1. Maybe it should be just `var e = this.getSource();` instead?
2. What are you doing exactly to get this error?

**Comment by Karmalakas** [comment]
I figured out, if I want to use _dev.js_ I have to add _moxie.js_, but still getting the same error:
`plupload.dev.js:2200 Uncaught TypeError: this.getSource is not a function`

`this` is a **Window** object. if I bind `this` (last line):

```
getNative: function() {
	var file = this.getSource().getSource();
	return o.inArray(o.typeOf(file), ['blob', 'file']) !== -1 ? file : null;
}.bind(this),
```

then `this` is **pluploadFile** object, but error remains. I have no idea how to fix this.

**Comment by aik099** [comment]
Is this error browser/OS-specific? Works on some OS/browser and doesn't on others.

Maybe this has something to do with your Plupload custom config. Also does it work on demo (http://www.plupload.com/examples/core)?

**Comment by Karmalakas** [comment]
So it seems jQuery somehow tries to call `getNative()`. I had this code:

```
pl.bind('FilesAdded', function(up, files) {
	var data = {file: files[0]};
	$.ajax({url: '/my_link', cache: false, data: data});
});
```

All I had to do, is replace `file: files[0]` to `file: JSON.parse(JSON.stringify(files[0]))` and it seems to be working. Don't know if it's a bug or not, but took a lot of time to figure out with a bit of help :)

**Comment by aik099** [comment]
Ah, you're sending an JS object and jQuery failed to transform it into string properly. You can try reporting this to jQuery instead. If you do please post that issue link in here as well.

**Comment by giox069** [comment]
Same problem for me: I upgraded from 1.6.1 to 2.1.8 and I get "TypeError: this.getSource is not a function" on last firefox and IE11.

**Comment by jayarjo** [comment]
@giox069 when does this error fire up? Provide a code and config and maybe a call stack dump...?

**Comment by giox069** [comment]
My problem is very similar to the @Karmalakas one: in the old code I had a jquery call to $.ajax with the following data:
`data: { op: 'new', files: uploader.files }`
This $.ajax call is fired after the user selected a file (so uploader.files is not empty), but before starting the uploader.
During the $.ajax call initialization, the pluploader getNative() function is called (why???), and it fails with the getSource() error in the subject. This happens for jquery 1.6.1 and the last 2.1.4 too.

So yes, it's jquery calling your getNative() when it does conversion of the array. But it worked with plupload 1.X.

My workaround was to build a new array of simpler objects, with only "name" and "size" properties. Calling then $.ajax with the followind data
`data: { op: 'new', files: my_simpler_array }`
works.

**Comment by jayarjo** [comment]
Hm... actually we never meant it to work with jQuery in such way. I need to experiment a bit. But in general what you said you ended up with, would my solution to your scenario.
